sudo: required
dist: trusty
language: node_js
node_js:
  - '8.11.3'
install:
  - npm install -g truffle
  - npm install
script:
  - npm run test:cov
before_script:
  - testrpc > /dev/null &
  - sleep 5
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls